version: '2'


services:
    mongo-express:
        image: mongo-express
        restart: always
        mem_limit: 1024m
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
        ports:
            - "8081:8081"
    mongo:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet

    sonarqube:
      image: sonarqube
      ports:
        - "9000:9000"
      networks:
        - sonarnet
      environment:
        - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
        
    db:
      image: postgres
      networks:
        - sonarnet
      environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar
      volumes:
        - postgresql:/var/lib/postgresql
        # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
        - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: